"""Removed  column

Revision ID: 1999f6ecaba9
Revises: ef55734ddf23
Create Date: 2024-11-20 15:44:22.525482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1999f6ecaba9'
down_revision = 'ef55734ddf23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=256), nullable=False))
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint('uq_vehicles_name', type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=60), nullable=False))
        batch_op.create_unique_constraint('uq_vehicles_name', ['name'])
        batch_op.alter_column('price',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('image')

    # ### end Alembic commands ###
