"""empty message

Revision ID: 1eb4a2b9fb32
Revises: 692c718a25a2
Create Date: 2024-12-04 14:40:46.287021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb4a2b9fb32'
down_revision = '692c718a25a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_employees')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_no', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('contacts', sa.String(length=60), nullable=True))
        batch_op.drop_constraint('uq_employees_contact_details', type_='unique')
        batch_op.drop_column('contact_details')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_details', sa.VARCHAR(length=60), nullable=False))
        batch_op.create_unique_constraint('uq_employees_contact_details', ['contact_details'])
        batch_op.drop_column('contacts')
        batch_op.drop_column('id_no')

    op.create_table('_alembic_tmp_employees',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_no', sa.VARCHAR(length=60), nullable=False),
    sa.Column('contacts', sa.VARCHAR(length=60), nullable=False),
    sa.Column('name', sa.VARCHAR(length=60), nullable=False),
    sa.Column('position', sa.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_employees'),
    sa.UniqueConstraint('contacts', name='uq_employees_contacts'),
    sa.UniqueConstraint('id_no', name='uq_employees_id_no')
    )
    # ### end Alembic commands ###
