"""empty message

Revision ID: 374a21f87e88
Revises: e9f7ed728c42
Create Date: 2024-11-20 16:22:30.143072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374a21f87e88'
down_revision = 'e9f7ed728c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('email', name=op.f('uq_customers_email')),
    sa.UniqueConstraint('phone', name=op.f('uq_customers_phone'))
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('position', sa.String(length=60), nullable=False),
    sa.Column('contact_details', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees'))
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('invoice_id', name=op.f('uq_payments_invoice_id')),
    sa.UniqueConstraint('payment_id', name=op.f('uq_payments_payment_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('employees')
    op.drop_table('customers')
    # ### end Alembic commands ###
