"""Dropped invoice id column

Revision ID: 9bb00bb382a6
Revises: 1af7ae0ef0d1
Create Date: 2024-12-05 12:51:34.252273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb00bb382a6'
down_revision = '1af7ae0ef0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_employees')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.alter_column('id_no',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('contacts',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_employees_contacts'), ['contacts'])
        batch_op.create_unique_constraint(batch_op.f('uq_employees_id_no'), ['id_no'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=70),
               existing_nullable=False)
        batch_op.drop_constraint('uq_payments_invoice_id', type_='unique')
        batch_op.drop_column('invoice_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.INTEGER(), nullable=False))
        batch_op.create_unique_constraint('uq_payments_invoice_id', ['invoice_id'])
        batch_op.alter_column('payment_id',
               existing_type=sa.String(length=70),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_employees_id_no'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_employees_contacts'), type_='unique')
        batch_op.alter_column('contacts',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('id_no',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)

    op.create_table('_alembic_tmp_employees',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_no', sa.VARCHAR(length=60), nullable=False),
    sa.Column('contacts', sa.VARCHAR(length=60), nullable=False),
    sa.Column('name', sa.VARCHAR(length=60), nullable=False),
    sa.Column('position', sa.VARCHAR(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_employees'),
    sa.UniqueConstraint('contacts', name='uq_employees_contacts'),
    sa.UniqueConstraint('id_no', name='uq_employees_id_no')
    )
    # ### end Alembic commands ###
