"""empty message

Revision ID: e5c6e0f3af42
Revises: 374a21f87e88
Create Date: 2024-11-20 21:26:31.351050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c6e0f3af42'
down_revision = '374a21f87e88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_employees_contact_details'), ['contact_details'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_employees_contact_details'), type_='unique')

    # ### end Alembic commands ###
