"""empty message

Revision ID: ebc626e70d5e
Revises: 88d56d8bfffc
Create Date: 2024-11-20 21:37:19.702549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc626e70d5e'
down_revision = '88d56d8bfffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('id_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_no', sa.VARCHAR(length=60), nullable=False))

    # ### end Alembic commands ###
